---
# ==========================================
# Java Configuration
# ==========================================
java_package: "openjdk-17-jdk-headless"
java_home: "/usr/lib/jvm/java-17-openjdk-amd64"

# ==========================================
# Spark Configuration
# ==========================================
spark_version: "3.5.8"
spark_hadoop_version: "3"
spark_checksum: "sha512:5d5d2e6e111182ee1210d4a46a17ae27107c7ccc70433da0ded3d8197e027f949b00445bb5678ed0c1d5c59f12993d9b9ed12e43686d5aad89a9ec570e93a083"

# Parent installation directory (in case you want to change it)
spark_install_parent_dir: "/opt"
# Actual installation directory (/opt/spark-3.5.8-bin-hadoop3)
spark_destination_dir: "{{ spark_install_parent_dir }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}"
# Where the symlink points to, which is independent of the version as it will always be /opt/spark
spark_link_dir: "/opt/spark"

# The download URL
spark_download_url: "https://dlcdn.apache.org/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}.tgz"

# ==========================================
# Spark Credentials
# ==========================================
spark_user: "spark"
spark_group: "spark"

# ==========================================
# Hadoop (HDFS) Configuration
# ==========================================
hadoop_version: "3.3.6"
hadoop_install_parent_dir: "/opt"
hadoop_destination_dir: "{{ hadoop_install_parent_dir }}/hadoop-{{ hadoop_version }}"
hadoop_link_dir: "/opt/hadoop"

hadoop_download_url: "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
hadoop_checksum_download_url: "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz.sha512"
hadoop_checksum: "sha512:de3eaca2e0517e4b569a88b63c89fae19cb8ac6c01ff990f1ff8f0cc0f3128c8e8a23db01577ca562a0e0bb1b4a3889f8c74384e609cd55e537aada3dcaa9f8a"

# The Identity that owns the HDFS data
hadoop_user: "hadoop"
hadoop_group: "hadoop"

# HDFS Configuration
# This number represents the number of times a piece of data is replicated across different nodes in the HDFS cluster.
# 3 is usually a good default for production, but this value has to be greater than or equal to the number of worker nodes in your cluster.
hdfs_replication_factor: 3
