# ==========================================
# 1. Common Configuration (Run on ALL nodes)
# ==========================================
- name: Apply Common Configuration
  hosts: all
  become: yes
  remote_user: user
  roles:
    - common # Installs vim, curl, htop, net-tools
    - java
    - python
    - monitoring # Cloud Monitoring/Logging
    - hadoop_base # HDFS
    - spark_base # Spark
  tags: common

# ==========================================
# 2. Master Node Configuration
# ==========================================
- name: Apply Master Node Configuration
  hosts: gcp_role_master
  become: yes
  remote_user: user
  roles:
    - hadoop_master # HDFS Master Node Configuration
    - spark_master # Spark Master Node Configuration
  tags: master

# ==========================================
# 3. Master Node Configuration
# ==========================================
- name: Apply Worker Node Configuration
  hosts: gcp_role_worker
  become: yes
  remote_user: user
  roles:
    - hadoop_worker # HDFS Worker Node Configuration
    - spark_worker # Spark Worker Node Configuration
  tags: worker

# ==========================================
# 4. Edge Node Configuration
# ==========================================
- name: Apply Edge Node Configuration (Configure Edge Node and Deploy Spark Artifacts)
  hosts: gcp_role_edge
  become: yes
  remote_user: user
  roles:
    - spark_artifacts # Configure Edge Node and Deploy Spark Jobs/Data (including HDFS directories and uploads)
  tags: spark_artifacts
