name: Deploy Infrastructure

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: 'enseeiht-spark-lab'
  LOCATION: 'europe-west1'
  PROJECT_NUMBER: '177424230750'
  SERVICE_ACCOUNT_ID: 'github-actions-sa'
  #SERVICE_ACCOUNT_EMAIL: '${{ env.SERVICE_ACCOUNT_ID }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
  SERVICE_ACCOUNT_EMAIL: 'github-actions-sa@enseeiht-spark-lab.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_POOL_ID: 'github-pool'
  WORKLOAD_IDENTITY_PROVIDER_ID: 'github-provider'
  #WORKLOAD_IDENTITY_PROVIDER: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ env.WORKLOAD_IDENTITY_PROVIDER_ID }}'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/177424230750/locations/global/workloadIdentityPools/github-pool/providers/github-provider'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          # Pass Terraform variables as environment variables
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
          TF_VAR_project_number: ${{ env.PROJECT_NUMBER }}
          TF_VAR_ssh_public_key_ruddy: ${{ secrets.SSH_PUBLIC_KEY_RUDDY }}
          TF_VAR_ssh_public_key_landry: ${{ secrets.SSH_PUBLIC_KEY_LANDRY }}
        run: |
          terraform -chdir=./terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          # Pass Terraform variables as environment variables
          TF_VAR_project_id: ${{ env.PROJECT_ID }}
          TF_VAR_project_number: ${{ env.PROJECT_NUMBER }}
          TF_VAR_ssh_public_key_ruddy: ${{ secrets.SSH_PUBLIC_KEY_RUDDY }}
          TF_VAR_ssh_public_key_landry: ${{ secrets.SSH_PUBLIC_KEY_LANDRY }}
        run: |
          terraform -chdir=./terraform apply -auto-approve -input=false tfplan
